# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''

menus:
  en-US:
    - {name: 'Home',              url: 'en-US/index'}
    - {name: 'Who is Francine?',  url: 'en-US/whoIsFrancine'}
    - {name: 'Rates',             url: 'en-US/rates'}
    - {name: 'Contact',           url: 'en-US/contact'}
  fr-CA:
    - {name: 'Accueil',           url: 'fr-CA/index'}
    - {name: 'Qui est Francine?', url: 'fr-CA/whoIsFrancine'}
    - {name: 'Tarifs',            url: 'fr-CA/rates'}
    - {name: 'Contact',           url: 'fr-CA/contact'}

menu_languages:
  - {name: 'Francais', url: 'fr-CA/index'}
  - {name: 'Anglais',  url: 'en-US/index'}

contact_form_languages:
  en-US:
    name: 'Name'
    email: 'Email'
    message: 'Message'
    send: 'Send'
  fr-CA:
    name: 'Nom'
    email: 'Courriel'
    message: 'Message'
    send: 'Envoyer'

test_languages:
  en-US: '© 2025 All right reserved'
  fr-CA: '© 2025 Tous droits réservés'

copyright_languages:
  en-US: '© 2025 All right reserved'
  fr-CA: '© 2025 Tous droits réservés'